name: upnp2
version: 3.0.12
description: Universal Plugin and Play Host/Client. This package can be used to discover upnp devices, invoke actions as well as spin up an upnp server.
homepage: https://github.com/daniel-naegele/upnp.dart
repository: https://github.com/daniel-naegele/upnp.dart

dependencies:
  xml: ^6.1.0
  crypto: ^3.0.1
environment:
  sdk: ^3.5.4
dev_dependencies:
  lints: ^5.0.0
  test: any
